# Generated by Django 5.0.2 on 2024-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_import_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')]),
        ),
    ]
